import type { Metadata } from "next";
import Link from "next/link";
import { conferencePublications, journalArticles, preprints, type Publication } from "../data";
import { PageHero, SectionHeading, Site } from "../components/SiteChrome";

export const metadata: Metadata = { title: "Publications | Jibin John, PhD", description: "Complete scholarly record organized as peer-reviewed journal articles, preprints and published conference abstracts." };

function PublicationList({ items }: { items: Publication[] }) {
  return <div className="full-publication-list">{items.map((item, index) => <article className="full-publication" key={`${item.title}-${item.year}-${item.venue}-${index}`}><div className="pub-index"><strong>{String(index + 1).padStart(2, "0")}</strong><span>{item.year}</span></div><div><p className="pub-venue">{item.venue} · {item.citation}</p><h3>{item.title}</h3><p className="pub-authors">{item.authors.split(/(J\. John)/g).map((part, partIndex) => part === "J. John" ? <mark key={partIndex}>{part}</mark> : part)}</p>{item.note && <p className="pub-note">{item.note}</p>}</div><a href={item.href} target="_blank" rel="noreferrer" aria-label={`Open ${item.title}`}>↗</a></article>)}</div>;
}

export default function PublicationsPage() {
  return <Site active="Publications"><PageHero eyebrow="Publications & scholarly work" title="A complete record, organized by publication type." intro="Peer-reviewed journal articles, current preprints and formally published conference abstracts are separated so each contribution is easy to understand and verify." actions={<><a className="button button-primary" href="#journal-articles">Journal articles</a><a className="button button-secondary" href="#preprints">Preprints</a></>} aside={<div className="stat-stack"><div><strong>{journalArticles.length}</strong><span>Journal articles</span></div><div><strong>{preprints.length}</strong><span>Preprints</span></div><div><strong>{conferencePublications.length}</strong><span>Published abstracts</span></div></div>} />
    <nav className="page-subnav" aria-label="Publication categories"><a href="#journal-articles">Peer-reviewed articles</a><a href="#preprints">Preprints</a><a href="#conference-publications">Conference publications</a><Link href="/conferences">Attendance & presentations</Link></nav>
    <section className="section page-shell" id="journal-articles"><SectionHeading eyebrow="Peer-reviewed journal articles" title={`${journalArticles.length} articles across psychiatric genetics, genomics and related fields.`} intro="Author lists are shown in publication order, with J. John representing Jibin John as published." /><PublicationList items={journalArticles} /></section>
    <section className="section alternate-section" id="preprints"><div className="page-shell"><SectionHeading eyebrow="Preprints" title="Current and historical preprint records." intro="Preprints are kept separate from peer-reviewed journal articles and linked to their DOI records." /><PublicationList items={preprints} /></div></section>
    <section className="section page-shell" id="conference-publications"><SectionHeading eyebrow="Published conference abstracts" title={`${conferencePublications.length} abstracts published in journal supplements and proceedings.`} intro="This category records formally published conference outputs. The separate Conferences page identifies first-author records and distinguishes authorship from confirmed personal attendance." /><PublicationList items={conferencePublications} /></section>
    <section className="profile-links-bar"><div className="page-shell"><p>For current indexing and citation metrics, use the live scholarly profiles.</p><div><a className="button button-primary" href="https://scholar.google.com/citations?user=vBDV0QkAAAAJ&hl=en" target="_blank" rel="noreferrer">Google Scholar ↗</a><a className="button button-secondary" href="https://pubmed.ncbi.nlm.nih.gov/?term=jibin+john+" target="_blank" rel="noreferrer">PubMed ↗</a></div></div></section>
  </Site>;
}
