import type { Metadata } from "next";
import { coauthoredConferenceContributions, conferencePublications, confirmedConferences, firstAuthorConferencePublications, type Publication } from "../data";
import { PageHero, SectionHeading, Site } from "../components/SiteChrome";

export const metadata: Metadata = { title: "Conferences | Jibin John, PhD", description: "Confirmed conference attendance and presentations, published abstracts, and coauthored conference contributions." };

function AuthorLine({ authors }: { authors: string }) {
  return <>{authors.split(/(J\. John)/g).map((part, index) => part === "J. John" ? <mark key={index}>{part}</mark> : part)}</>;
}

function ConferenceCards({ items }: { items: Publication[] }) {
  return <div className="abstract-grid">{items.map((item) => <a href={item.href} target="_blank" rel="noreferrer" key={item.title}><span>{item.year}</span><p>{item.venue} · {item.citation}</p><h3>{item.title}</h3><small><AuthorLine authors={item.authors} /></small></a>)}</div>;
}

export default function ConferencesPage() {
  const additionalPublishedAbstracts = conferencePublications.filter((item) => !item.authors.startsWith("J. John"));

  return <Site active="Conferences"><PageHero eyebrow="Conferences & presentations" title="Participation separated by evidence and role." intro="Confirmed personal presentations and attendance are listed separately from coauthored conference outputs where my attendance was not established. This avoids implying that I personally attended every meeting attached to a coauthored abstract." aside={<div className="stat-stack"><div><strong>{confirmedConferences.length}</strong><span>Confirmed presentation / attendance records</span></div><div><strong>{conferencePublications.length}</strong><span>Published abstracts</span></div><div><strong>{coauthoredConferenceContributions.length}</strong><span>Coauthored contributions</span></div></div>} />
    <section className="section page-shell"><SectionHeading eyebrow="Confirmed participation" title="Presentations and meetings I attended." intro="Evidence includes presenter schedules, posters, abstracts, registrations, awards or CV records." /><div className="conference-timeline">{confirmedConferences.map((item) => <article key={`${item.date}-${item.title}`}><div className="conference-date">{item.date}</div><div className="conference-marker" /><div className="conference-body"><p>{item.location}</p><h3>{item.meeting}</h3><span>{item.role}</span><h4>{item.title}</h4></div></article>)}</div></section>
    <section className="section alternate-section"><div className="page-shell"><SectionHeading eyebrow="First-author conference publications" title={`${firstAuthorConferencePublications.length} published abstracts led by Jibin John.`} intro="These records place Jibin John first in the published author order. Authorship is distinct from attendance; personally confirmed presentations are documented in the section above." /><ConferenceCards items={firstAuthorConferencePublications} /></div></section>
    <section className="section page-shell"><SectionHeading eyebrow="Additional published conference record" title={`${additionalPublishedAbstracts.length} coauthored abstracts with formal publication records.`} intro="All citations remain available without crowding the main conference timeline." /><details className="record-disclosure"><summary>View {additionalPublishedAbstracts.length} additional published abstracts</summary><div className="disclosure-grid"><ConferenceCards items={additionalPublishedAbstracts} /></div></details></section>
    <section className="section page-shell"><SectionHeading eyebrow="Coauthored conference contributions" title="Scholarly contributions where personal attendance is not established." intro="These records document coauthorship only. They do not claim that I physically or virtually attended the meeting or delivered the presentation." /><details className="record-disclosure"><summary>View all {coauthoredConferenceContributions.length} coauthored records</summary><div className="coauthor-table">{coauthoredConferenceContributions.map((item) => <div key={`${item.year}-${item.title}`}><strong>{item.year}</strong><span>{item.meeting}</span><p>{item.title}</p></div>)}</div></details></section>
    <section className="section invited-section"><div className="page-shell"><SectionHeading eyebrow="Invited & educational activities" title="Talks, workshops and teaching." /><div className="workflow-cards"><article><span>June 2022</span><h3>Research and Career Journey in Bioinformatics</h3><p>Online talk documented through meeting and feedback records; organizer details remain under verification.</p></article><article><span>2021–2022</span><h3>Clinical exome analysis and variant interpretation</h3><p>CDFD training in alignment, variant calling, prioritization and interpretation for clinicians, faculty, students and researchers.</p></article><article><span>2021–2022</span><h3>RNA-seq analysis training</h3><p>Institutional workshop and project-support activity at CDFD.</p></article><article><span>Earlier roles</span><h3>Whole-exome and genotyping analysis</h3><p>Guidance for graduate students, interns, clinicians and researchers at the University of Delhi.</p></article></div></div></section>
  </Site>;
}
