import type { Metadata } from "next";
import { researchPrograms } from "../data";
import { PageHero, ScienceFigure, SectionHeading, Site } from "../components/SiteChrome";

export const metadata: Metadata = { title: "Research | Jibin John, PhD", description: "Research programs in statistical genetics, imaging genetics, psychiatric genomics, proteomic Mendelian randomization and clinical genomics." };

export default function ResearchPage() {
  return <Site active="Research"><PageHero eyebrow="Research" title="Understanding complex disease through integrated genomic evidence." intro="My current work focuses on statistical genetics, psychiatric and cognitive genomics, imaging-derived phenotypes, circulating proteins and reproducible analytical systems." actions={<><a className="button button-primary" href="#programs">Research programs</a><a className="button button-secondary" href="/publications">Related publications</a></>} aside={<ScienceFigure type="omics" />} />
    <section className="section page-shell"><SectionHeading eyebrow="Research framework" title="From genomic signal to interpretable biology." intro="The work spans discovery, validation, functional interpretation and reliable delivery." /><div className="workflow-large"><div><strong>01</strong><h3>Genomic data</h3><p>GWAS, WES/WGS, pQTL, eQTL, sQTL, imaging-derived phenotypes and public reference resources.</p></div><i>→</i><div><strong>02</strong><h3>Statistical analysis</h3><p>QC, meta-analysis, multi-trait models, genetic correlation, causal inference and rare-variant testing.</p></div><i>→</i><div><strong>03</strong><h3>Biological interpretation</h3><p>Genes, proteins, pathways, tissues, cell types, networks, drug targets and convergent evidence.</p></div><i>→</i><div><strong>04</strong><h3>Research output</h3><p>Reproducible scripts, validated results, figures, reports, manuscripts and training materials.</p></div></div></section>
    <section className="section impact-section" id="programs"><div className="page-shell"><SectionHeading eyebrow="Research portfolio" title="Current and foundational programs." intro="Each program combines a scientific question, a defined data landscape and a reproducible analytical approach." /><div className="program-grid">{researchPrograms.map((program, index) => <article className="program-card" key={program.title}><span>0{index + 1}</span><p>{program.metric}</p><h3>{program.title}</h3><div className="program-line" /><p>{program.copy}</p></article>)}</div></div></section>
    <section className="section page-shell"><SectionHeading eyebrow="Methods in context" title="Four connected analytical perspectives." /><div className="figure-grid"><article><ScienceFigure type="gwas" /><h3>Population-scale association</h3><p>Discover and compare common-variant signals across complex phenotypes.</p></article><article><ScienceFigure type="family" /><h3>Family and rare-variant genomics</h3><p>Use inheritance and functional evidence to prioritize high-impact variation.</p></article><article><ScienceFigure type="omics" /><h3>Multi-omics interpretation</h3><p>Connect statistical association with proteins, expression, cells and pathways.</p></article><article><ScienceFigure type="pipeline" /><h3>Reproducible systems</h3><p>Design auditable workflows that can be rerun, reviewed and transferred.</p></article></div></section>
    <section className="contact-ribbon"><div className="page-shell"><div><p className="eyebrow light"><span />Explore the evidence</p><h2>Research programs are connected to publications and conference outputs.</h2></div><div><a className="button button-light" href="/publications">Publications</a><a className="button button-outline-light" href="/conferences">Conferences</a></div></div></section>
  </Site>;
}
